default: &default
  host: localhost
  adapter: postgresql
  database: localtower_dummy
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: <%= ENV["LOCALTOWER_PG_USERNAME"] %>
  password: <%= ENV["LOCALTOWER_PG_PASSWORD"] %>

test:
  <<: *default
  database: localtower_dummy_test

production:
  <<: *default
