source 'https://rubygems.org'

gem "rails", "~> 7.1.0"
gem 'pg'
gem 'puma'

group :development, :test do
  localtower_path = File.expand_path(File.join(File.dirname(__FILE__), '..', '..'))
  gem "localtower", path: localtower_path
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
